language: python
cache: pip
python:
  - "3.6"
  - "3.7"
sudo: required

install:
  pip install -r requirements-develop.txt

script:
  pytest --cov=brendapy

after_success:
   pip install codecov; codecov
